name: Java CI/CD to AWS ECR

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Build Docker Image
      run: docker build -t kand2021:${{ github.sha }} .
      
    - name: configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-west-1

    - name: Login to Amazon ECR
      if: github.ref == 'refs/heads/main'
      uses: aws-actions/amazon-ecr-login@v1

    - name: Tag and push image to Amazon ECR
      if: github.ref == 'refs/heads/main'
      env:
        ECR_REGISTRY: '244530008913.dkr.ecr.eu-west-1.amazonaws.com'
        ECR_REPOSITORY: 'kand2021'
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag kand2021:${IMAGE_TAG} $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
        docker tag kand2021:${IMAGE_TAG} $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest